config/routes.rb
Rails.application.routes.draw do

  get 'request_for_notification/:id/:id1' => 'cars#request_for_notification' ,:as => 'request_for_notification'
  get 'checkout_car' => 'bookings#checkout_car' ,:as => 'checkout_car'
  get 'member/admin_watch_user' => 'members#admin_watch_user' , :as => 'admin_watch_user'
  get 'member/admin_show_page' => 'members#admin_show_page' , :as => 'admin_stuff'
  match 'member/:id' => 'members#destroy' , :via => [:put,:get] ,:method => :delete , :as => 'member_destroy'
  match 'members' => 'members#create' , :via => :put
  resources :members
  get 'bookings/:id/edit' => 'bookings#edit' ,:as => 'edit_booking'
  get 'bookings' => 'bookings#index'
  match 'booking/:id' => 'bookings#update' ,:via => [:get,:patch],:as => 'booking'
  get 'check_out_history_car/:id' => 'bookings#check_out_history_car' , :as => 'check_out_history_car'
  match 'reserve_car/:id' => 'bookings#reserve_car', :via => [:put,:get], :as => 'reserve_car'
  match 'reserve_car/:id' => 'bookings#reserve!', :via => [:post], :as => 'reserve'
  match 'reserve_now/:id' => 'bookings#reserve_now', :via => [:post], :as => 'reserve_now'
  match 'delete_reservation/:id' => 'bookings#delete_booking', :via => [:get], :method => :delete, :as => 'delete_reservation'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_car_for_user' , :via => [:get], :as => 'reserve_car_for_user'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_for_user' , :via => [:put], :as => 'reserve_for_user'
  get 'show_booking_history' => 'bookings#show_booking_history' ,:as => 'show_booking_history'
  devise_for :users
  resources :cars
  root :to => 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/booking.rb
class Booking < ApplicationRecord
  acts_as_paranoid
  self.table_name = "acts_as_bookable_bookings"

  def self.checking_status
    cars = Car.all
    cars.each do |car|
      unless Booking.find_by_bookable_id(car.id) == nil
        unless Booking.find_by_bookable_id(car.id).time_start == nil
          if car.status == "Reserved" and Time.now  > Booking.find_by_bookable_id(car).time_start + 30.minutes and Time.now < Booking.find_by_bookable_id(car).time_end
            Booking.where(:bookable_id => car.id , :booker_id => Booking.find_by_bookable_id(car).booker_id).last.destroy
            car.status = "Available"
            car.save!

          elsif car.status == "Checked out" and Time.now + 4.hours >= Booking.find_by_bookable_id(car).time_end
            booker_id = Booking.find_by_bookable_id(car).booker_id
            mailer = User.find_by_id(booker_id)
            ExampleMailer.sample_email(mailer).deliver
            Booking.where(:bookable_id => car.id , :booker_id => booker_id).last.destroy
            car.status = "Available"
            car.save!
          end
        end
      end
    end
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_time_from_params, only: [:reserve!, :reserve_for_user]
  before_action :set_current_user, only: [:show_booking_history, :reserve_car, :reserve!, :reserve_now]
  before_action :set_car_from_params, only: [:check_out_history_car, :reserve_car, :reserve!, :reserve_now, :reserve_for_user, :delete_booking]

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find params[:id]
    respond_to do |format|
      if @booking.update(:bookable_id=>params[:booking][:bookable_id],:booker_id=>params[:booking][:booker_id],:time_start=>params[:booking][:time_start],:time_end=>params[:booking][:time_end])
        format.html { redirect_to bookings_path, notice: 'Booking was successfully updated.' }
        format.json { render :show, status: :ok, location: @booking }
      else
        format.html { render :edit }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @bookings=Booking.all
  end

  def check_out_history_car
    @books1 = @car.bookings
  end

  def checkout_car
    booking = Booking.where( :booker_id => current_user.id)
    car = Car.find(booking.first.bookable_id)
    car.status = "Checked out"
    car.save!
    flash[:notice] = "Car successfully checked out!"
    redirect_to root_path
  end

  def show_booking_history
    @book1 = Booking.with_deleted.where(:booker_id => @user.id).where.not(:deleted_at => nil)
  end

  def reserve_car
  end

  def reserve!
    car_is_reserved = Booking.find_by_bookable_id(@car.id)
    user_has_booked_a_car = Booking.where(:booker_id => @user.id).last
    if user_has_booked_a_car
      flash[:notice] = "You have already booked a car!"
      redirect_to(root_path)
    elsif car_is_reserved && @time_start < car_is_reserved.time_end
      flash[:notice] = "Please try booking the car for a different time!"
      redirect_to(root_path)
    elsif car_is_reserved.nil? || @time_start > car_is_reserved.time_end
      book_car(@car, @user, @time_start, @time_end, "Reserved")
    end
  end

  def reserve_now
    @time_start = Time.now.to_datetime
    @time_end = (@time_start + params[:time_end].to_i.hours).to_datetime
    car_is_reserved = Booking.find_by_bookable_id(@car.id)
    user_has_booked_a_car = Booking.find_by_booker_id(@user.id)
    if user_has_booked_a_car
      flash[:notice] = "You have already booked a car!"
      redirect_to(root_path)
    elsif car_is_reserved
      flash[:notice] = "Please try booking the car for a different time!"
      redirect_to(root_path)
    else
      if user_has_booked_a_car.nil?
        book_car(@car, @user, @time_start, @time_end, "Reserved")
      end
    end
  end

  def delete_booking
    if current_user.admin? or current_user.super_admin?
      user = Booking.find_by_bookable_id(@car).booker_id
    else
      user = current_user
    end
    user_to_be_deleted = User.find(user)
    unless Booking.where(:bookable_id => @car).count > 1
      @car.update_attribute :status, "Available"
      if @car.register_email and !@car.user.nil?
        mailer = User.find_by_email(@car.user)
        ExampleMailer.sample_email(mailer).deliver
        @car.user = nil
        @car.save!
      end
    end
    delete_reservation(@car, user_to_be_deleted)
    respond_to do |format|
      flash[:notice] = "Reservation has been cancelled!"
      format.html { redirect_to(root_path) }
      format.js
    end
  end

  def delete_reservation(car_to_be_deleted, user_to_be_deleted)
    Booking.where(:bookable_id => car_to_be_deleted.id , :booker_id => user_to_be_deleted).last.destroy
  end

  def reserve_car_for_user
    @users = User.all
  end

  def reserve_for_user
    @useremail = params[:selected_user]
    @user = User.find_by_email(@useremail)
    book_car(@car, @user, @time_start, @time_end, "Reserved")
  end

  def book_car(car, user, time_start, time_end, status)
    begin
      user.book! car, time_start: time_start, time_end: time_end
      respond_to do |format|
        car.update_attribute :status, status
        flash[:notice] = "Car has been successfully reserved!"
        format.html { redirect_to(root_path) }
        format.js
      end
    rescue ActsAsBookable::AvailabilityError
      flash[:notice] = "Please try booking the car for a different time!"
      redirect_to(root_path)
    end
  end

  private
    def set_time_from_params
      if params[:booking][:time_start] == ""
        flash.now[:notice] = "Date cannot be blank!"
        redirect_to(reserve_car_for_user_path)
      else
        @time_start = params[:booking][:time_start].to_datetime
        @time_end = (@time_start + params[:time_end].to_i.hours).to_datetime
      end
    end

    def set_current_user
      @user = current_user
    end

    def set_car_from_params
      @car = Car.find(params[:id])
    end
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def calculate_rental_charge
    unless current_user.admin? && current_user.super_admin?
      @booked_car_records = Booking.with_deleted.find_by_booker_id(current_user.id)
      unless @booked_car_records.nil?
        @booked_car = @booked_car_records.bookable_id
        @hourly_rate = Car.find(@booked_car).hourly_rental_rate
        @time_diff = ((Booking.with_deleted.find_by_booker_id(current_user.id).time_end - Booking.with_deleted.find_by_booker_id(current_user.id).time_start) / 3600).round
        @rental_charge = @hourly_rate * @time_diff
      end
    end
  end

  def license_plate(t)
    Car.where(:id => t.bookable_id).first.license_plate
  end

  def model(t)
    Car.where(:id => t.bookable_id).first.model
  end

  def manufacturer(t)
    Car.where(:id => t.bookable_id).first.manufacturer
  end

  def booking
    @booking = Booking.find_by_bookable_id(params[:id])
  end

  def find_user_name(t)
    User.find(t.booker_id).name
  end

  def find_user_email
    @user_email = User.find_by_id(booking.booker_id).email
  end

  def start_time
    @start_time = booking.time_start
  end

  def end_time
    @end_time = booking.time_end
  end

  def normal_users
    User.where(:admin => false, :super_admin => false).collect(&:email)
  end

end

app/views/bookings/_form.html.erb
<h6>Information about the car you have chosen: </h6>
<div class = "text-center">
<%= form_for car, :url => url_for(:controller => 'bookings', :action => 'reserve!' ), :method => 'post' do |f| %>
    <% if car.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

          <ul>
            <% car.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <table class = "table table-striped table-bordered">
        <thead>
        <tr>
          <th>License plate</th>
          <th>Manufacturer</th>
          <th>Model</th>
          <th>Hourly rental rate</th>
          <th>Style</th>
          <th>Location</th>
          <th>Status</th>
        </tr>
        </thead>

        <tbody>
            <tr>
              <td><%= link_to car.license_plate, car %></td>
              <td><%= car.manufacturer %></td>
              <td><%= car.model %></td>
              <td><%= car.hourly_rental_rate %></td>
              <td><%= car.style %></td>
              <td><%= car.location %></td>
              <td><%= car.status %></td>
            </tr>
        </tbody>
      </table>

      Select start time
      <%= datetime_field(:booking, :time_start, min: Date.today, max: Date.today + 7.days, :step => 1.hour ,:discard_seconds => true) %>
      <span style = "font-size: 12px">Format: yyyy-mm-dd hh:mm:ss</span>
      <br>
      Number of hours for which you want to rent the car:
      <%=select_tag(:time_end, options_for_select(1..10))%>
      <br>
      <%= f.submit 'Reserve' %>
    </div>
<% end %>
</div>

app/views/bookings/_form_booking.html.erb
<%= form_for(booking) do |f| %>
   <% if booking.errors.any? %>
     <div id="error_explanation">
       <h2><%= pluralize(booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

       <ul>
         <% booking.errors.full_messages.each do |message| %>
                 <li><%= message %></li>
             <% end %>
       </ul>
     </div>
   <% end %>

   <div class="field">
     Car ID
     <%= f.text_field :bookable_id %>
   </div>

   <div class="field">
     Booker ID
     <%= f.text_field :booker_id %>
   </div>

   <div class="field">
     <%= f.label :time_start %>
     <%= f.datetime_field :time_start %>
   </div>

   <div class="field">
     <%= f.label :time_end %>
     <%= f.datetime_field :time_end %>
   </div>

   <div class="actions">
     <%= f.submit %>
   </div>
<% end %>

app/views/bookings/_rent_immediately.html.erb
<div class = "text-center">

  OR

<%= form_for car, :url => url_for(:controller => 'bookings', :action => 'reserve_now' ), :method => 'post' do |f| %>
    Number of hours for which you want to rent the car:
    <%= select_tag(:time_end, options_for_select(1..10)) %>
    <br>
    <%= submit_tag 'Rent immediately' %>
<% end %>
</div>

app/views/bookings/check_out_history_car.html.erb
<table class = "table table-striped table-bordered">
  <thead>
  <tr>
    <th>License plate</th>
    <th>Model</th>
    <th>Style</th>
    <th>Booked by</th>
    <th>Start Time</th>
    <th>End Time</th>
  </tr>
  </thead>

  <tbody>
  <tr>
  <% @books1.each do |t| %>
    <td><%= @car.license_plate %></td>
    <td><%= @car.model %></td>
    <td><%= @car.style %></td>
    <td><%= find_user_name(t) %></td>
    <td><%= t.time_start %></td>
    <td><%= t.time_end %></td>
  </tr>
  <%end%>
   </tbody>
</table>
<%= link_to 'Back',root_path, class: "btn btn-primary btn-md text-white" %>

app/views/bookings/edit.html.erb
<h1>Editing Car</h1>
<%= render 'form_booking', booking: @booking %>
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Current bookings</h1>
<table class="table table-striped table-bordered">
   <thead>
 <tr>
     <th>Booking Id</th>
     <th>Car Id</th>
     <th>Renter Id</th>
     <th>Time start</th>
     <th>Time end</th>
     <th colspan="3">Actions</th>
   </tr>
 </thead>

   <tbody>
 <% @bookings.each do |booking| %>
         <tr>
           <td><%=booking.id%></td>
           <td><%=booking.bookable_id%></td>
           <td><%=booking.booker_id%></td>
           <td><%=booking.time_start%></td>
           <td><%=booking.time_end%></td>
           <td><%=link_to 'Edit',edit_booking_path(booking)%></td>
         </tr>
     <% end %>
 </tbody>
 </table>

<%= link_to 'Back',root_path, class: "btn btn-primary btn-md text-white" %>

app/views/bookings/reserve_car.html.erb
<%= render 'form', car: @car %>
<%= render 'rent_immediately', car: @car %>

app/views/bookings/reserve_car_for_user.html.erb
<% if booking %>
  <br>
  This car has been booked by user:
    <%= find_user_email %>
    from <%= start_time %> to <%= end_time %>
    <br><br>
    <%= link_to 'Cancel reservation', delete_reservation_path(params[:id]), class: "btn btn-primary btn-md text-white" %>
<% end %>
<br>
<br>
<%= form_for :booking, :url => url_for(:controller => 'bookings', :action => 'reserve_for_user' ), :method => 'put' do |f| %>
    User for which you want to book this car
    <%= select_tag 'selected_user', options_for_select(normal_users), include_blank: false  %>
    <br><br>
    Select from date
    <%= datetime_field(:booking, :time_start, min: Date.today, max: Date.today + 7.days, :step => 1.hour ,:discard_seconds => true) %>
    <span style = "font-size: 12px">Format: yyyy-mm-dd hh:mm:ss</span>
    <br><br>
    Number of hours for which you want to rent the car:
    <%=select_tag(:time_end, options_for_select(1..10))%>

    <br><br>
    <%= submit_tag 'Reserve', class: "btn btn-primary btn-md text-white" %>
    <%= link_to 'Back', root_path, class: "btn btn-primary btn-md text-white" %>
<% end %>

app/views/bookings/show_booking_history.html.erb
<t3>Checkout Details</t3>
<table class = "table table-striped table-bordered">
    <thead>
  <tr>
      <th>License plate</th>
      <th>Model</th>
      <th>Manufacturer</th>
      <th>Booking start time</th>
      <th>Booking end Time</th>
    </tr>
  </thead>
  
  <tbody>
    Your pending rent is $ <%= calculate_rental_charge %>
    <br>
    <% @book1.each do |t| %>
      <tr>
        <td><%= license_plate(t) %></td>
        <td><%= model(t) %></td>
        <td><%= manufacturer(t) %></td>
        <td><%= t.time_start %></td>
        <td><%= t.time_end %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<%= link_to 'Back', root_path, class: "btn btn-primary btn-md text-white" %>