config/routes.rb
Rails.application.routes.draw do

  get 'request_for_notification/:id/:id1' => 'cars#request_for_notification' ,:as => 'request_for_notification'
  get 'checkout_car' => 'bookings#checkout_car' ,:as => 'checkout_car'
  get 'member/admin_watch_user' => 'members#admin_watch_user' , :as => 'admin_watch_user'
  get 'member/admin_show_page' => 'members#admin_show_page' , :as => 'admin_stuff'
  match 'member/:id' => 'members#destroy' , :via => [:put,:get] ,:method => :delete , :as => 'member_destroy'
  match 'members' => 'members#create' , :via => :put
  resources :members
  get 'bookings/:id/edit' => 'bookings#edit' ,:as => 'edit_booking'
  get 'bookings' => 'bookings#index'
  match 'booking/:id' => 'bookings#update' ,:via => [:get,:patch],:as => 'booking'
  get 'check_out_history_car/:id' => 'bookings#check_out_history_car' , :as => 'check_out_history_car'
  match 'reserve_car/:id' => 'bookings#reserve_car', :via => [:put,:get], :as => 'reserve_car'
  match 'reserve_car/:id' => 'bookings#reserve!', :via => [:post], :as => 'reserve'
  match 'reserve_now/:id' => 'bookings#reserve_now', :via => [:post], :as => 'reserve_now'
  match 'delete_reservation/:id' => 'bookings#delete_booking', :via => [:get], :method => :delete, :as => 'delete_reservation'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_car_for_user' , :via => [:get], :as => 'reserve_car_for_user'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_for_user' , :via => [:put], :as => 'reserve_for_user'
  get 'show_booking_history' => 'bookings#show_booking_history' ,:as => 'show_booking_history'
  devise_for :users
  resources :cars
  root :to => 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
  include IceCube
  acts_as_bookable time_type: :range

  validates_length_of :license_plate, :minimum => 7, :maximum => 7,:too_short => 'should be 7 characters long.', :too_long => 'should be 7 characters long.', uniqueness: true
  validates_numericality_of(:hourly_rental_rate)

  def self.search(search, search_by)
    where("#{search_by} LIKE ?", "%#{search}%")
  end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /cars
  # GET /cars.json

  def index
    @cars = Car.all
    @user_has_booked_a_car = Booking.find_by_booker_id(current_user.id)
    @options_for_search = @cars.attribute_names.select {|i| i.include?("location") || i.include?("model") || i.include?("manufacturer") || i.include?("style") || i.include?("status" )}
    if !params[:search].blank? and !params[:search_by].blank?
      @cars = Car.search(params[:search], params[:search_by]).order("created_at DESC")
    else
      @recipes = Car.all.order("created_at DESC")
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)
    @car.schedule = IceCube::Schedule.new(Time.now.beginning_of_day, duration: 24.hours)
    @car.schedule.add_recurrence_rule IceCube::Rule.daily
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    if Booking.where(:bookable_id => @car.id).exists?
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'That car is booked by a user!' }
        format.json { head :no_content }
      end
    else
      @car.destroy
      respond_to do |format|
        format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def request_for_notification
    @car = Car.find(params[:id])
    @user = User.find(params[:id1])
    @car.update_attribute(:user, @user.email)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:license_plate, :manufacturer, :model, :hourly_rental_rate, :style, :location,
                                  :status, :time_start, :time_end, :register_email)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
  def instance_variables
    @booking = Booking.find_by_bookable_id(car.id)
  end

  def current_user_is_admin?
    current_user.admin?
  end

  def current_user_is_super_admin?
    current_user.super_admin?
  end

  def user_booking(current_user, car)
    Booking.where(:booker_id => current_user.id, :bookable_id => car.id)
  end

  def check_time(current_user, car)
    Time.now >= user_booking(current_user, car).last.time_start
  end
end

app/views/cars/_admin_actions.html.erb
<tbody>
<% @cars.each do |car| %>
    <tr>
      <td><%= link_to car.license_plate, car %></td>
      <td><%= car.manufacturer %></td>
      <td><%= car.model %></td>
      <td><%= car.hourly_rental_rate %></td>
      <td><%= car.style %></td>
      <td><%= car.location %></td>
      <td><%= car.status %></td>

      <% if car.status == 'Checked out' %>
        <% unless user_booking(current_user, car).exists? %>
        <td><%= link_to 'Register for notification', request_for_notification_path(car.id, current_user.id) %></td>
        <% end %>
      <%end%>

      <% if current_user.admin? || current_user.super_admin? %>
         <td><%= link_to 'View checkout history', check_out_history_car_path(car.id) %></td>
      <%end%>

      <% if user_booking(current_user, car).exists? && check_time(current_user, car) %>
          <% unless car.status == "Checked out" %>
            <td><%= link_to 'Checkout car', checkout_car_path %></td>
          <% end %>
      <%end%>

<% unless current_user_is_admin? && current_user_is_super_admin? %>

    <% if user_booking(current_user, car).exists? %>
      <td><%= link_to car.status == "Reserved" ? 'Cancel reservation' : 'Return car', delete_reservation_path(car) %></td>
    <% else %>
      <% if @user_has_booked_a_car || @booking %>
        <td>Can't book!</td>
      <% else %>
        <td class = "link_color"><%= link_to 'Reserve or Rent', reserve_car_path(car) %></td>
      <% end %>
    <% end %>

<% else %>
    <td class = "link_color"><%= link_to 'Manage user reservations', reserve_car_for_user_path(car) %></td>
<% end %>

<% if current_user_is_admin? || current_user_is_super_admin? %>
    <td class = "link_color"><%= link_to 'Edit', edit_car_path(car) %></td>
    <td class = "link_color"><%= link_to 'Delete', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<% end %>
</tr>

<% end %>
</tbody>

app/views/cars/_form.html.erb
<%= form_for(car) do |f| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license_plate %>
    <%= f.text_field :license_plate %>
  </div>

  <div class="field">
    <%= f.label :manufacturer %>
    <%= f.text_field :manufacturer %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :hourly_rental_rate %>
    <%= f.text_field :hourly_rental_rate %>
  </div>

  <div class="field">
    <%= f.label :style %>
    <%= f.select "style", options_for_select(["Coupe", "Sedan", "SUV"]), include_blank: false %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cars/_form_for_email.html.erb
<%= form_for(@car) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
        <% @car.errors.full_messages.each do |message| %>
           <li><%= message %></li>
        <% end %>
      </ul>

    </div>
  <% end %>
     
  <div class="field">
    <%= f.label :register_email %>
    <%= f.select "register_email", options_for_select([['Yes', true], ['No', false]])%>
  </div>
     
  <div class="actions">
    <%= f.submit "Register", class: "btn btn-primary btn-md text-white" %>
  </div>
     
<%end%>

app/views/cars/_search.html.erb
<%= form_tag(cars_path, :method => "get", id: "search-form") do %>
    Search by
    <%= select_tag 'search_by', options_for_select(@options_for_search)  %>
    <%= text_field_tag :search, params[:search], placeholder: "Search" %>
    <%= submit_tag "Search", :name => nil, class: "btn btn-primary btn-md text-white" %>
<% end %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>
<%= render 'cars/search' %>
<% if @cars.blank? %>
    <h4>There are no cars containing the term <%= params[:search] %> in <%= params[:search_by] %>.</h4>
    <h7><%=link_to 'Show All Cars',cars_path%> </h7><br/>
<% end %>
<br>
<h1 style = "display: inline-block">List of Cars </h1>
<% if current_user.admin? %>
    <a href= "cars/new" class="btn btn-primary btn-md text-white", style = "display: inline-block; position: absolute; right: 30px" >Add a new car</a>
<% end %>
<table class = "table table-striped table-bordered">
  <thead>
    <tr>
      <th>License plate</th>
      <th>Manufacturer</th>
      <th>Model</th>
      <th>Hourly rental rate</th>
      <th>Style</th>
      <th>Location</th>
      <th>Status</th>
      <th colspan="4">Actions</th>
    </tr>
  </thead>

  <%= render 'admin_actions' %>


</table>

<br>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', cars_path %>

app/views/cars/request_for_notification.html.erb
<h1>Register for Email Notification</h1>
<%= render 'form_for_email' %>

<%= link_to 'Show', @car %>
<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>License plate:</strong>
  <%= @car.license_plate %>
</p>

<p>
  <strong>Manufacturer:</strong>
  <%= @car.manufacturer %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Hourly rental rate:</strong>
  <%= @car.hourly_rental_rate %>
</p>

<p>
  <strong>Style:</strong>
  <%= @car.style %>
</p>

<p>
  <strong>Location:</strong>
  <%= @car.location %>
</p>

<p>
  <strong>Status:</strong>
  <%= @car.status %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>