config/routes.rb
Rails.application.routes.draw do

  get 'request_for_notification/:id/:id1' => 'cars#request_for_notification' ,:as => 'request_for_notification'
  get 'checkout_car' => 'bookings#checkout_car' ,:as => 'checkout_car'
  get 'member/admin_watch_user' => 'members#admin_watch_user' , :as => 'admin_watch_user'
  get 'member/admin_show_page' => 'members#admin_show_page' , :as => 'admin_stuff'
  match 'member/:id' => 'members#destroy' , :via => [:put,:get] ,:method => :delete , :as => 'member_destroy'
  match 'members' => 'members#create' , :via => :put
  resources :members
  get 'bookings/:id/edit' => 'bookings#edit' ,:as => 'edit_booking'
  get 'bookings' => 'bookings#index'
  match 'booking/:id' => 'bookings#update' ,:via => [:get,:patch],:as => 'booking'
  get 'check_out_history_car/:id' => 'bookings#check_out_history_car' , :as => 'check_out_history_car'
  match 'reserve_car/:id' => 'bookings#reserve_car', :via => [:put,:get], :as => 'reserve_car'
  match 'reserve_car/:id' => 'bookings#reserve!', :via => [:post], :as => 'reserve'
  match 'reserve_now/:id' => 'bookings#reserve_now', :via => [:post], :as => 'reserve_now'
  match 'delete_reservation/:id' => 'bookings#delete_booking', :via => [:get], :method => :delete, :as => 'delete_reservation'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_car_for_user' , :via => [:get], :as => 'reserve_car_for_user'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_for_user' , :via => [:put], :as => 'reserve_for_user'
  get 'show_booking_history' => 'bookings#show_booking_history' ,:as => 'show_booking_history'
  devise_for :users
  resources :cars
  root :to => 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_logout.html.erb
<ul class = "navbar-brand link_color">
  <%if user_signed_in?%>
      <%=link_to "Logout",destroy_user_session_path, :method => :get%>
  <%else%>
      <%=link_to "Login", new_user_session_path%>
  <%end%>

</ul>

app/views/layouts/_navigation_bar.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded sticky-top">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span>Menu</span>
  </button>
  <%= render 'layouts/logout' %>
  <div class="collapse navbar-collapse" id="navbarText">
        <div class="nav-link colored_link" >
          <h5><%= link_to "Home", root_path %></h5>

          <%if !current_user.nil? %>
              <h5><%=link_to 'Edit your profile', edit_user_registration_path%></h5>
              <% unless current_user.super_admin? && current_user.admin? %>
                <h5><%= link_to 'Your check out history', show_booking_history_path %></h5>
              <% end %>

              <% if current_user.super_admin? || current_user.admin? %>
                <h5><%=link_to 'List of admins & super admins', admin_stuff_path %></h5>
                <h5><%=link_to 'List of Customers', admin_watch_user_path%></h5>
                <h5><%= link_to 'Edit a booking for a customer', bookings_path %></h5>
              <% end %>
          <%end%>
        </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= javascript_include_tag :defaults %>


<html>
  <head>
    <title>Car Rental App</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/navigation_bar' %><br/>
  </head>
  <body>
  <%unless current_user.nil?%>
    <div class = "text-center">
      <h2>Welcome, <%=current_user.name%>! </h2>
    </div>
  <%end%>
  <div class = "text-center">
    <%= yield %><br/>
  </div>
  </body>
</html>