config/routes.rb
Rails.application.routes.draw do

  get 'request_for_notification/:id/:id1' => 'cars#request_for_notification' ,:as => 'request_for_notification'
  get 'checkout_car' => 'bookings#checkout_car' ,:as => 'checkout_car'
  get 'member/admin_watch_user' => 'members#admin_watch_user' , :as => 'admin_watch_user'
  get 'member/admin_show_page' => 'members#admin_show_page' , :as => 'admin_stuff'
  match 'member/:id' => 'members#destroy' , :via => [:put,:get] ,:method => :delete , :as => 'member_destroy'
  match 'members' => 'members#create' , :via => :put
  resources :members
  get 'bookings/:id/edit' => 'bookings#edit' ,:as => 'edit_booking'
  get 'bookings' => 'bookings#index'
  match 'booking/:id' => 'bookings#update' ,:via => [:get,:patch],:as => 'booking'
  get 'check_out_history_car/:id' => 'bookings#check_out_history_car' , :as => 'check_out_history_car'
  match 'reserve_car/:id' => 'bookings#reserve_car', :via => [:put,:get], :as => 'reserve_car'
  match 'reserve_car/:id' => 'bookings#reserve!', :via => [:post], :as => 'reserve'
  match 'reserve_now/:id' => 'bookings#reserve_now', :via => [:post], :as => 'reserve_now'
  match 'delete_reservation/:id' => 'bookings#delete_booking', :via => [:get], :method => :delete, :as => 'delete_reservation'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_car_for_user' , :via => [:get], :as => 'reserve_car_for_user'
  match 'reserve_car_for_user/:id' => 'bookings#reserve_for_user' , :via => [:put], :as => 'reserve_for_user'
  get 'show_booking_history' => 'bookings#show_booking_history' ,:as => 'show_booking_history'
  devise_for :users
  resources :cars
  root :to => 'cars#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /members
  # GET /members.json
  def index
    @members = User.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = User.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json

  def create
    @member = User.new(member_params)
    if current_user.admin? || current_user.super_admin?
      if params[:UserType] == "1"
        @member.admin = true
      end
      if params[:UserType]== "2"
        @member.super_admin = true
      end
    end
    respond_to do |format|
      if @member.save
        format.html { redirect_to root_path, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    if Booking.where(:booker_id => @member.id).exists?
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'That member has booked a car!' }
        format.json { head :no_content }
      end
    else
      @member.destroy
      respond_to do |format|
        format.html { redirect_to root_path, notice: 'Member was successfully destroyed.' }
        format.json { head :no_content }
      end
    end
  end

  def admin_show_page
    @user1 = User.where(admin: true, super_admin: false)
  end

  def admin_watch_user

  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:user).permit(:name,:email,:password,:admin,:super_admin)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_for member, url: members_path(member),html:{ method: :put} do |f| %>
  <% if member.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
      <% member.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
        <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

    <% if current_user.super_admin? %>
      <%= f.label :UserType %><br />
      <%= select_tag(:UserType, options_for_select([['Admin', 1], ['SuperAdmin', 2],['User',3]], 3))%>

    <% elsif current_user.admin? %>
      <%= f.label :UserType %><br />
      <%= select_tag(:UserType, options_for_select([['Admin', 1],['User',2]], 2))%>
    <% end %>

    <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/members/admin_show_page.html.erb
<% if !current_user.nil? %>
  <% if current_user.super_admin? %>
    <%= link_to 'Create Super admin', new_member_path %><br/>
    <h4>List & Details of super admins</h4>
    <table class = "table table-striped table-bordered" style = "width: 50%">
      <thead>
        <tr>
          <th>Email</th>
          <th>Name</th>
        </tr>
      </thead>

      <% user = super_admin_true %>

      <% user.each do |user| %>
        <tr>
          <td> <%=user.email%> </td>
          <td> <%=user.name%> </td>
        </tr>
      <%end%>
    </table>
    <%end%>

        <br>

    <% if current_user.admin? or current_user.super_admin? %>
      <%= link_to 'Create new admin', new_member_path %><br/>
      <h4>List & Details of Admins</h4>
        <table class = "table table-striped table-bordered ", style = "width: 50%" >
        <thead>
          <tr>
            <th>Email</th>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>
        <% @user1.each do |user| %>
          <tbody>
          <tr>
            <td> <%= user.email %> </td>
            <td> <%= user.name %> </td>
            <td class = "link_color">
              <%= link_to 'Destroy', member_destroy_path(user.id), data: { confirm: "Are you sure?" } %>
            </td>
          </tr>
          </tbody>
        <%end%>
        </table>
    <%end%>
<%end%>
<%=link_to 'Back', root_path, class: "btn btn-primary btn-md text-white" %>

app/views/members/admin_watch_user.html.erb
<h3>List of customers</h3>

<%user1 = User.where(admin: false ,super_admin: false) %>

<table class = "table table-striped table-bordered" style = "width: 50%">

<thead>
  <tr>
    <th>Email</th>
    <th>Name</th>
    <th colspan="3">Actions</th>
  </tr>
</thead>

<%user1.each do |user| %>
  <tbody>
  <tr>
    <td><%= user.email %> </td>
    <td><%= user.name %></td>
    <td><%= link_to 'Destroy', member_destroy_path(user.id), data: { confirm: "Are you sure?" } %></td>
  </tr>
  </tbody>
<%end%>
</table>

<%= link_to 'Back',root_path, class: "btn btn-primary btn-md text-white" %>

app/views/members/edit.html.erb
<h1>Editing Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Show', @member %> |
<%= link_to 'Back', members_path %>

app/views/members/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Members</h1>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @members.each do |member| %>
      <tr>
        <td><%=member.name%></td>
        <td><%=member.email%></td>
        <td><%= link_to 'Edit', edit_member_path(member) %></td><br/>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Member', new_member_path %>

app/views/members/new.html.erb
<h1>New Member</h1>

<%= render 'form', member: @member %>

<%= link_to 'Back', members_path %>

app/views/members/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_member_path(@member) %> |
<%= link_to 'Back', members_path %>